### PR TITLE
[*.css] Refactoring of *.css files 

### PR DESCRIPTION
**Pull request by hankpeeples**

### CODE REVIEW

**Comment by TylerAdamMartinez** [comment]
Could you make the picture of the poster in the pop up menu a standard size just like it is in the poster card section

**Comment by hankpeeples** [comment]
> Could you make the picture of the poster in the pop up menu a standard size just like it is in the poster card section

I could but that would severely mess up their aspect ratios and make them all blurry or stretched. I think it looks fine how it is now.

**Comment by TylerAdamMartinez** [comment]
Crop it then if the click the image it shows the entire image in a pop up

**Comment by hankpeeples** [comment]
CleanShot 2022-07-29 at 16 56 02
How's this instead of another popup? Just scales on hover.

**Comment by TylerAdamMartinez** [comment]
This is amazing. Is it possible that it will zoom up after hovering it after says 2 to 4 seconds and slow down the transition time between zoomed and non-zoomed?

**Comment by hankpeeples** [comment]
> This is amazing. Is it possible that it will zoom up after hovering it after says 2 to 4 seconds and slow down the transition time between zoomed and non-zoomed?

I think it's pretty unnecessary to complicate it like that.

**Comment by TylerAdamMartinez** [comment]
https://user-images.githubusercontent.com/57375362/181865505-f34ec7a1-0be7-4185-a302-79ddee71c964.mp4

**Comment by TylerAdamMartinez** [comment]
Yay or nay on the style change?

**Comment by hankpeeples** [comment]
> Yay or nay on the style change? Keep in mind, that I can always push it up for you to improve upon it.

Yeah, that looks fine. I would say reduce the amount of time it takes to zoom and un-zoom a little. I feel like it's always better to have faster interactive animations.

**Review by TylerAdamMartinez — APPROVED** [review]

**Pull request merged**
